import 'package:flutter/services.dart';

Map<LogicalKeyboardKey, int> keyMap = Map.unmodifiable({
  LogicalKeyboardKey.keyA : 0x0A,
  LogicalKeyboardKey.keyB : 0x1C,
  LogicalKeyboardKey.keyC : 0x14,
  LogicalKeyboardKey.keyD : 0x12,
  LogicalKeyboardKey.keyE : 0x0E,
  LogicalKeyboardKey.keyF : 0x15,
  LogicalKeyboardKey.keyG : 0x1A,
  LogicalKeyboardKey.keyH : 0x1D,
  LogicalKeyboardKey.keyI : 0x21,
  LogicalKeyboardKey.keyJ : 0x22,
  LogicalKeyboardKey.keyK : 0x25,
  LogicalKeyboardKey.keyL : 0x2A,
  LogicalKeyboardKey.keyM : 0x24,
  LogicalKeyboardKey.keyN : 0x27,
  LogicalKeyboardKey.keyO : 0x26,
  LogicalKeyboardKey.keyP : 0x29,
  LogicalKeyboardKey.keyQ : 0x3E,
  LogicalKeyboardKey.keyR : 0x11,
  LogicalKeyboardKey.keyS : 0x0D,
  LogicalKeyboardKey.keyT : 0x16,
  LogicalKeyboardKey.keyU : 0x1E,
  LogicalKeyboardKey.keyV : 0x1F,
  LogicalKeyboardKey.keyW : 0x09,
  LogicalKeyboardKey.keyX : 0x17,
  LogicalKeyboardKey.keyY : 0x19,
  LogicalKeyboardKey.keyZ : 0x0C,

  LogicalKeyboardKey.digit0 : 0x23,
  LogicalKeyboardKey.digit1 : 0x38,
  LogicalKeyboardKey.digit2 : 0x3B,
  LogicalKeyboardKey.digit3 : 0x08,
  LogicalKeyboardKey.digit4 : 0x0B,
  LogicalKeyboardKey.digit5 : 0x10,
  LogicalKeyboardKey.digit6 : 0x13,
  LogicalKeyboardKey.digit7 : 0x18,
  LogicalKeyboardKey.digit8 : 0x1B,
  LogicalKeyboardKey.digit9 : 0x20,

  LogicalKeyboardKey.space : 0x3c,
  LogicalKeyboardKey.shiftLeft : 0x0F,
  LogicalKeyboardKey.enter : 0x01,
});